// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ventas.Infrastructure.Data;

#nullable disable

namespace Ventas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ventas.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<bool>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("NumericValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StringValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Variable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Configuration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Identificador del sistema",
                            NumericValue = 0m,
                            StringValue = "TEST",
                            Variable = "M&MID"
                        },
                        new
                        {
                            Id = 2,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Nombre de la empresa",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "empresa"
                        },
                        new
                        {
                            Id = 3,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Fecha inicio de la empresa",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "fechaInicio"
                        },
                        new
                        {
                            Id = 4,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "CUIT / CUIL de la empresa",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "cuit"
                        },
                        new
                        {
                            Id = 5,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Condición fiscal de la empresa",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "condicionFiscalId"
                        },
                        new
                        {
                            Id = 6,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Alias de ARCA",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "arcaAlias"
                        },
                        new
                        {
                            Id = 7,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Dirección certificado de ARCA",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "arcaCertificado"
                        },
                        new
                        {
                            Id = 8,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Clave del certificado de ARCA",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "arcaClave"
                        },
                        new
                        {
                            Id = 9,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Token del sistema",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "tokenSystem"
                        },
                        new
                        {
                            Id = 10,
                            Active = 1,
                            BoolValue = false,
                            Deleted = 0,
                            Description = "Último número usado en la caja diaria",
                            NumericValue = 0m,
                            StringValue = "",
                            Variable = "cajaDiariaNumero"
                        });
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<int>("Document")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxConditionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaxConditionId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.DailyBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyBox");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Entity");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<decimal>("DescountPercentage")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("IncreasePercentage")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.PointOfSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PointOfSale");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.PointOfSaleVoucherType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<int>("Numeration")
                        .HasColumnType("int");

                    b.Property<int>("PointOfSaleId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PointOfSaleId");

                    b.HasIndex("VoucherTypeId");

                    b.ToTable("PointOfSaleVoucherType");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeBar")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaxRateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TaxRateId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.StateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("StateEntity");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.TaxCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaxCondition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = 1,
                            Code = 5,
                            Deleted = 0,
                            Description = "CONSUMIDOR FINAL"
                        },
                        new
                        {
                            Id = 2,
                            Active = 1,
                            Code = 1,
                            Deleted = 0,
                            Description = "RESPONSABLE INSCRIPTO"
                        },
                        new
                        {
                            Id = 3,
                            Active = 1,
                            Code = 4,
                            Deleted = 0,
                            Description = "SUJETO EXENTO"
                        },
                        new
                        {
                            Id = 4,
                            Active = 1,
                            Code = 6,
                            Deleted = 0,
                            Description = "RESPONSABLE MONOTRIBUTO"
                        },
                        new
                        {
                            Id = 5,
                            Active = 1,
                            Code = 7,
                            Deleted = 0,
                            Description = "SUJETO NO CATEGORIZADO"
                        });
                });

            modelBuilder.Entity("Ventas.Domain.Entities.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxRate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = 1,
                            Code = "0005",
                            Deleted = 0,
                            Description = "IVA 21%",
                            Percentage = 21m
                        },
                        new
                        {
                            Id = 2,
                            Active = 1,
                            Code = "0004",
                            Deleted = 0,
                            Description = "IVA 10,5%",
                            Percentage = 10.5m
                        },
                        new
                        {
                            Id = 3,
                            Active = 1,
                            Code = "0003",
                            Deleted = 0,
                            Description = "IVA 0%",
                            Percentage = 0m
                        },
                        new
                        {
                            Id = 4,
                            Active = 1,
                            Code = "0006",
                            Deleted = 0,
                            Description = "IVA 27%",
                            Percentage = 27m
                        },
                        new
                        {
                            Id = 5,
                            Active = 1,
                            Code = "0008",
                            Deleted = 0,
                            Description = "IVA 5%",
                            Percentage = 5m
                        },
                        new
                        {
                            Id = 6,
                            Active = 1,
                            Code = "0009",
                            Deleted = 0,
                            Description = "IVA 2,5%",
                            Percentage = 2.5m
                        });
                });

            modelBuilder.Entity("Ventas.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PointOfSaleId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PointOfSaleId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountNet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountVAT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CAEExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DailyBoxId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("StateEntityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DailyBoxId");

                    b.HasIndex("StateEntityId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherTypeId");

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VoucherDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountNet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherDetail");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VoucherPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherPayment");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VoucherType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("VoucherType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = 1,
                            Code = "OR",
                            Deleted = 0,
                            Description = "ORDEN DE COMPRA"
                        },
                        new
                        {
                            Id = 2,
                            Active = 1,
                            Code = "001",
                            Deleted = 0,
                            Description = "FACTURA A"
                        },
                        new
                        {
                            Id = 3,
                            Active = 1,
                            Code = "004",
                            Deleted = 0,
                            Description = "RECIBO A"
                        },
                        new
                        {
                            Id = 4,
                            Active = 1,
                            Code = "006",
                            Deleted = 0,
                            Description = "FACTURA B"
                        },
                        new
                        {
                            Id = 5,
                            Active = 1,
                            Code = "009",
                            Deleted = 0,
                            Description = "RECIBO B"
                        });
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.TaxCondition", "TaxCondition")
                        .WithMany("Customers")
                        .HasForeignKey("TaxConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxCondition");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.PointOfSaleVoucherType", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.PointOfSale", "PointOfSale")
                        .WithMany("PointOfSaleVoucherTypes")
                        .HasForeignKey("PointOfSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.VoucherType", "VoucherType")
                        .WithMany("PointOfSaleVoucherTypes")
                        .HasForeignKey("VoucherTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointOfSale");

                    b.Navigation("VoucherType");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Product", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.TaxRate", "TaxRate")
                        .WithMany("Products")
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.StateEntity", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Entity", "Entity")
                        .WithMany("StateEntities")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.User", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.PointOfSale", "PointOfSale")
                        .WithMany("Users")
                        .HasForeignKey("PointOfSaleId");

                    b.HasOne("Ventas.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("PointOfSale");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Customer", "Customer")
                        .WithMany("Vouchers")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Ventas.Domain.Entities.DailyBox", "DailyBox")
                        .WithMany("Vouchers")
                        .HasForeignKey("DailyBoxId");

                    b.HasOne("Ventas.Domain.Entities.StateEntity", "StateEntity")
                        .WithMany()
                        .HasForeignKey("StateEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.VoucherType", "VoucherType")
                        .WithMany()
                        .HasForeignKey("VoucherTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DailyBox");

                    b.Navigation("StateEntity");

                    b.Navigation("User");

                    b.Navigation("VoucherType");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VoucherDetail", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.Product", "Product")
                        .WithMany("VoucherDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Voucher", "Voucher")
                        .WithMany("VoucherDetails")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VoucherPayment", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("VoucherPayments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ventas.Domain.Entities.Voucher", "Voucher")
                        .WithMany("VoucherPayments")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.DailyBox", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Entity", b =>
                {
                    b.Navigation("StateEntities");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("VoucherPayments");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.PointOfSale", b =>
                {
                    b.Navigation("PointOfSaleVoucherTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Product", b =>
                {
                    b.Navigation("VoucherDetails");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.TaxCondition", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.TaxRate", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("VoucherDetails");

                    b.Navigation("VoucherPayments");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VoucherType", b =>
                {
                    b.Navigation("PointOfSaleVoucherTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
